apiVersion: v2
name: app
description: A Helm chart for banking system applications
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: infra
    version: "0.1.0"
    repository: "file://../infrastructure-chart"
    condition: infra.enabled