apiVersion: v1
kind: ConfigMap
metadata:
  name: common-config
data:
  LOKI_URL: "http://loki.{{ .Release.Namespace }}.svc.cluster.local:3100/loki/api/v1/push"
  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: "http://tempo.{{ .Release.Namespace }}.svc.cluster.local:9411"
  SPRING_KAFKA_BOOTSTRAP-SERVERS: "broker.{{ .Release.Namespace }}.svc.cluster.local:29092"
  USER_SERVICE_URL: "http://user-service.{{ .Release.Namespace }}.svc.cluster.local:8080"
  ACCOUNT_SERVICE_URL: "http://account-service.{{ .Release.Namespace }}.svc.cluster.local:8081"
  TRANSACTION_SERVICE_URL: "http://transaction-service.{{ .Release.Namespace }}.svc.cluster.local:8082"
  PAYMENT_SERVICE_URL: "http://payment-service.{{ .Release.Namespace }}.svc.cluster.local:8083"